### ISSUE TITLE
parameter set causing segfault

### ISSUE THREAD

**Issue by lukashergt** [cmbant/CAMB#104]
Hi Anthony,

the following mini script causes a segmentation fault for me (both remotely on a cluster and locally on my laptop.):

```python
import camb
paramdict = {'omk': -0.28939992799376785, 
             'cosmomc_theta': 0.0104760482479651, 
             'ombh2': 0.02112253491320435, 
             'omch2': 0.03157962814172189, 
             'mnu': 0.06, 
             'tau': 0.2875826843383382}
p = camb.set_params(**paramdict)
r = camb.get_results(p)
cl = r.get_cmb_power_spectra()
```

As far as I can tell, `H0` is being set to zero and subsequently causes various `NaN` because of a devide by zero, but I don't know why this case does not throw "No solution for H0 inside of theta_H0_range" like in most other cases, i.e. why does scipy's `brentq` allow `H0` to be set to zero in the first place...?

* Can you reproduce the segfault with that script? 
* Any idea how this could be fixed?

Cheers,
Lukas

**Comment by cmbant** [comment]
Interesting one that. Seems scipy's brentq will happy return with a converged result if one of the boundaries is NaN.

I think the underlying issue is that this model's expansion turns around before dark energy can dominate for H0=100. Try fix in 
https://github.com/cmbant/CAMB/commit/277968ad979c74eac808011c3fa39dc09b453934
(which will raise error)

**Comment by lukashergt** [comment]
Thanks for your prompt fix, Antony! This did indeed take care of any problems with my curvature runs.
