### ISSUE TITLE
increasing max_transfer_redshifts

### ISSUE THREAD

**Issue by joezuntz** [cmbant/CAMB#107]
Hi Antony,

Do you have any thoughts on increasing `max_transfer_redshifts` from its present 150 value, to e.g. 500?

We've had models in lensing where it's useful to generate a fairly fine grid of z values, which can be limited by this number. There are alternative ways of dealing with this, but just increasing it is the most direct, and as far as I know doesn't have any major downsides apart from a very tiny memory usage increase?

Cheers,
Joe

**Comment by cmbant** [comment]
I've never seen a case where interpolating on 150 wasn't enough? Or is this more a matter of convenience where you want to not have to interpolate? When you go to small steps, it does reduce the separation between Runge-Kutta output points, which presumably does have some small overhead rather than using the adaptively-chosen step size. It can also be that splining on denser samplings give worse results if you start seeing derivatives dominated by numerical noise. However I've not investigated in detail, have you tried?

(It's also possible to use get_redshift_evolution() instead with whatever dynamically-allocated spacing you like.)

**Comment by joezuntz** [comment]
We haven't investigated this in detail, no - it was just based on the convergence of computed C_ell values in a specific case against another code, so it may have been some other simplistic calculation somewhere, like how the interpolation was done

I can investigate some more.  Thanks for the pointer on get_redshift_evolution; that sounds handy.  I'll close this for now if you're not keen.
