### ISSUE TITLE
Unexpected behaviour in pycamb: object persistence issue

### ISSUE THREAD

**Issue by msyriac** [cmbant/CAMB#26]
I have documented an issue in this iPython notebook here:
https://github.com/msyriac/orphics/blob/master/scripts/CAMBIssue.ipynb

(github should show the input and output cells as I last pushed it; if not let me know and I can paste the script here)

The basic issue is that I expected CAMBdata objects to remember what parameters were passed to them. So if I do:

```
camb_data1.comoving_radial_distance(1100)
camb_data2.comoving_radial_distance(1100)
```

where the two data objects had different parameters passed to them, I would expect the answers to be different. Instead, the answers correspond to the last set of parameters that were used in a calculation, possibly due to the way global variables are set in pycamb. (The iPython notebook above explicitly demonstrates this.)

Maybe this is a feature and not a bug, but it was unexpected for me! It has the potential to introduce nasty bugs in Fisher-matrix-like codes that perturb parameters, so I thought I'd post it here.

**Comment by cmbant** [comment]
Yes, when using any calculation function you need to call calc_background or one of the functions to calculate transfer functions before calling to make sure the correct background etc. are precomputed and being used.  Basically the only times when you can use multiple camb data instances is when accessing the computed and stored transfer functions; otherwise you should calculate everything you need with each set of parameters and store them yourself before changing the parameters.
