### ISSUE TITLE
Expected agreement between published Planck 2018 theory Cls and CAMB output

### ISSUE THREAD

**Issue by tilmantroester** [cmbant/CAMB#55]
I find deviations of ~0.1% at high ell and ~0.2% at low ell between the theory Cls published by Planck (e.g., `base_plikHM_TTTEEE_lowl_lowE.minimum.theory_cl`) and those produced by CAMB when using `inifiles/planck_2018.ini`:
![Planck_vs_CMAB_cls](https://user-images.githubusercontent.com/26582252/63597948-78a04580-c5b6-11e9-9c6c-38a3e26d01d5.png)
Code:
```python
import camb
import numpy as np
import matplotlib.pyplot as plt

ell, TT, TE, EE = np.loadtxt("COM_CosmoParams_base-plikHM_R3.01/base/plikHM_TTTEEE_lowl_lowE/base_plikHM_TTTEEE_lowl_lowE.minimum.theory_cl", 
                              unpack=True, usecols=[0,1,2,3])

p = camb.read_ini("CAMB/inifiles/planck_2018.ini")

# Set to values in plikHM_TTTEEE_lowl_lowE/base_plikHM_TTTEEE_lowl_lowE.minimum
p.ombh2 = 0.2237737E-01
p.omch2=0.1201035E+00
p.H0=0.6732178E+02
p.tau=0.5430138E-01

r = camb.get_results(p)
TT_camb, EE_camb, _, TE_camb = r.get_total_cls(CMB_unit="muK")[2:int(ell[-1])+1].T

fig, ax = plt.subplots(1, 2, sharey=True)
fig.subplots_adjust(wspace=0, left=0.2)

ax[0].semilogx(ell, TT_camb/TT-1, label="TT")
ax[1].plot(ell, TT_camb/TT-1)

ax[0].semilogx(ell, EE_camb/EE-1, label="EE")
ax[1].plot(ell, EE_camb/EE-1)

ax[0].set_ylabel("$C_\ell^{CAMB}/C_\ell^{Planck}-1$")
ax[0].set_xlabel("$\ell$")
ax[1].set_xlabel("$\ell$")

ax[1].set_ylim(-0.003, 0.003)
ax[0].legend()

fig.savefig("../plots/Planck_vs_CMAB_cls.png")
```

The deviations are even larger for `inifiles/planck_2018.ini`. Is this level of agreement to be expected?

**Comment by cmbant** [comment]
planck_2018.ini is based on base_plikHM_TTTEEE_lowl_lowE_lensing. There will be some small differences if using CAMB 1.x because some things have changed since the CAMB version used for the Planck analysis. The planck2018_acc.ini version of the file will also give differences, because the default settings are only designed to get this at Planck precision (e.g. the lensing is not accurate on small scales) but the acc one gets the spectrum to high accuracy to high L.

**Comment by cmbant** [comment]
Is there still a problem here?

**Comment by tilmantroester** [comment]
No, I think this can be closed.
