### ISSUE TITLE
Extrapolation when kmax not high enough is not really linear

### ISSUE THREAD

**Issue by joezuntz** [cmbant/CAMB#61]
`CMBdata.get_matter_power_interpolator` shows slightly odd behaviour when extrapolating matter power to higher k, depending on the kmax value, in a way that doesn't match previous camb versions.  This usually shows up in the NL power.

Because the extrapolation is cubic and the function only adds a single extrapolated point onto the end of the k array, you can end up with strange behaviour like up-ticks at high k.

See the code and figure below.

One solution would be to add a bunch more log-linearly extrapolated points to the array instead of just one.

Cheers,
Joe

```
import numpy as np
import matplotlib.pyplot as plt
import camb

# Example invocation from docs
cp = camb.set_params(ns=1, H0=67, ombh2=0.022, omch2=0.1, w=-0.95, Alens=1.2, lmax=2000, 
                     WantTransfer=True, dark_energy_model='DarkEnergyPPF', kmax=1.0)

r = camb.get_results(cp)

P, z, k = r.get_matter_power_interpolator(nonlinear=True, return_z_k=True, extrap_kmax=500.)

k_plot = np.logspace(-4, np.log10(500), 300)
P_plot = P.P(0.0, k_plot)


plt.loglog(k_plot, P_plot)

# Maximum actual calculated value
plt.axvline(k.max(), color='r')

plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/220537/66588826-31314100-eb85-11e9-982c-c7729f958789.png)

**Comment by cmbant** [comment]
Good point, that would certainly be a simple fix. Which CAMB version are you comparing to, it didn't change recently I think? (it looks OK with kmax=10, which I think is what I usually use)

**Comment by joezuntz** [comment]
This was a comparison to the fortran equivalent, so very very old!

**Comment by cmbant** [comment]
Ah, I think the currently MatterPowerData_k still does the same as before: it does direct log-linear extrapolation outside the compute range. 

(With kmax=1 the extrapolation seems to be orders of magnitude off anyway)

**Comment by cmbant** [comment]
The Fortran function is still the same, it does direct linear extrapolation beyond the bound.

For this Python issue I think there was actually an indexing bug, as well as the issue with bicubic interpolation. In https://github.com/cmbant/CAMB/commit/fc024fe938ed844dbf42e6d257d3569d5dc1a486 I've changed it so that the gradient it pinned near the end point.  The new extrapolation accuracy looks like this:

![image](https://user-images.githubusercontent.com/3958819/66606827-d01c6400-ebaa-11e9-9716-adaf995d0c4c.png)

For linear it's much more accurate (should think about smarter extrapolation, c.f. https://github.com/cmbant/CAMB/issues/53).
